name: bandit

on: push

jobs:
  build:
    name: Bandit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2

      - name: Security check - Bandit
        uses: ./
        with:
          project_path: .trade
          ignore_failure: true