name: bandit

on: push

jobs:
  build:
    name: Bandit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - uses: jpetrucciani/bandit-check@master
      with:
        path: "./backend/app/app"
        bandit_flags: '-x ./backend/app/app/tests,backend/app/app/services/okx_core'
        skips: "B311,B105,B113,B307"