name: bandit

on: push

jobs:
  build:
    name: Bandit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - uses: jpetrucciani/bandit-check@master
    - name: Run bandit
      run: |
        bandit -x ./backend/app/app/tests,backend/app/app/services/okx_core -r ./backend/app/app -s "B311,B105,B113,B307"