name: bandit

on: push

jobs:
  build:
    name: Bandit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - uses: shundor/bandit-action@v1
      with:
        path: "./backend/app/app"
        excluded_paths: "./backend/app/app/tests,backend/app/app/services/okx_core"
        skips: "B311,B105,B113,B307"
